config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "zoom_breakouts#home"
    # Zoom Breakout Manager routes
  get 'zoom_breakouts/auth', to: 'zoom_breakouts#auth'
  get 'zoom_breakouts/install', to: 'zoom_breakouts#install'
  get 'zoom_breakouts/home', to: 'zoom_breakouts#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/zoom_breakout_session.rb
class ZoomBreakoutSession < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include DryCrud::Controllers
end

app/controllers/zoom_breakouts_controller.rb
# frozen_string_literal: true

require 'zoom_breakout_api'

class ZoomBreakoutsController < ApplicationController
  layout 'application'
  class ZoomAuthCodeError < StandardError; end
  class MissingZoomAccessTokenError < StandardError; end

  # Gets access and refresh tokens and stores them in Zoom Session for current user
  def auth
    request_code = request.parameters['code']

    if request_code.blank?
      msg = 'No Zoom auth code found. This route should only be hit when adding the Zoom Breakout Manager app ' \
            'from the Zoom interface, which will route you here with an authentication code from Zoom.'
      raise ZoomAuthCodeError, msg
    end

    token_response = ZoomBreakoutAPI.client.get_access_token(request_code)
    
    zm_breakout_session = ZoomBreakoutSession.last
    if zm_breakout_session
      zm_breakout_session.update!(access_token: token_response['access_token'], refresh_token: token_response['refresh_token'])
    else
      zm_breakout_session = ZoomBreakoutSession.create!(
        access_token: token_response['access_token'],
        refresh_token: token_response['refresh_token']
      )
    end
  end

  def install
    access_token = ZoomBreakoutSession.last&.access_token
    if access_token.blank?
      raise MissingZoomAccessTokenError, "No Zoom Access token found"
    end

    deep_link = ZoomBreakoutAPI.client.get_deep_link(access_token)
    redirect_to deep_link, allow_other_host: true
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoombreakouttest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% if content_for?(:css_js) %>
      <%= yield(:css_js) %>
    <% else %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag 'layouts/application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application' %>
    <% end %>
    
  </head>

  <body>
    <%= yield %>
    <%# <script src="https://appssdk.zoom.us/sdk.js"></script> %>
  </body>
</html>

app/views/zoom_breakouts/auth.html.erb
<% content_for(:headline) do %>
  Authorize Zoom Breakout Manager App
<% end %>

<div class="col-md-8">
  <p>Click <%= link_to 'here', zoom_breakouts_install_path %> to install the Zoom Breakout Manager app to use in your Zoom meetings.</p>
</div>

app/views/zoom_breakouts/home.html.erb
<% content_for :title, 'Zoom Breakout Manager' %>

<h1>
  Zoom Breakout Manager
</h1>

<div class="col-md-8">
  <button id="randomize-btn">Randomize breakout rooms</button>
</div>